version: '3.8'

services:
  postgres:
    container_name: implant_container
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ra1205
      POSTGRES_DB: implant_db
      PGDATA: /data/postgres
    volumes:
      - /data/pg:/data/postgres
